# nixpacks.toml

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",

  # Headless browser deps
  "glib", "nss", "nspr", "dbus", "at-spi2-core", "atk",
  "cups", "alsa-lib",
  "freetype", "fontconfig", "pango", "cairo", "gdk-pixbuf", "gtk3",
  "libdrm", "mesa", "mesa.drivers", "libxkbcommon",
  "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext",
  "xorg.libXfixes", "xorg.libXrandr", "xorg.libXrender", "xorg.libXi",
  "xorg.libxcb", "xorg.libXcursor", "xorg.libxshmfence", "xorg.libXinerama"
]

[start]
# 1) Download browsers into /root/.cache/ms-playwright (cached across restarts)
# 2) Show what got installed (debug)
# 3) Run your scraper
cmd = "echo '🔧 Installing Playwright browsers…' && python -m playwright install chromium firefox || true; ls -lah /root/.cache/ms-playwright || true; python -u main.py"
