[phases.setup]
nixPkgs = [
  "bash","coreutils","which",
  "glib","nss","nspr","freetype","fontconfig",
  "pango","cairo","gdk-pixbuf","gtk3","mesa",
  "libxkbcommon",
  "xorg.libX11","xorg.libXcomposite","xorg.libXdamage","xorg.libXext",
  "xorg.libXfixes","xorg.libXrandr","xorg.libXrender","xorg.libXi",
  "xorg.libxcb","xorg.libXcursor","xorg.libxshmfence","xorg.libXinerama"
]

[start]
cmd = "echo '🔧 Installing Playwright browsers…' && python -m playwright install chromium firefox || true; python -u main.py"
