# nixpacks.toml  — only add system libs + start command.
# Do NOT override the install phase; Nixpacks will detect Python from requirements.txt.

[phases.setup]
nixPkgs = [
  "bash", "coreutils", "which",
  "playwright-driver",        # provides Chromium/Firefox/WebKit + glue
  "glib", "nss", "nspr", "freetype", "fontconfig",
  "pango", "cairo", "gdk-pixbuf", "gtk3", "mesa",
  "libxkbcommon",
  "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext",
  "xorg.libXfixes", "xorg.libXrandr", "xorg.libXrender", "xorg.libXi",
  "xorg.libxcb", "xorg.libXcursor", "xorg.libxshmfence", "xorg.libXinerama"
]

[variables]
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
PLAYWRIGHT_BROWSERS_PATH = "/usr/lib/playwright"

[start]
cmd = "python -u main.py"
