# nixpacks.toml

[phases.setup]
# Python + pip + Playwright system browsers + all headless deps
nixPkgs = [
  "python311",
  "python311Packages.pip",

  # Browsers provided by Nix (Chromium/Firefox/WebKit with proper RPATH)
  "playwright-driver",

  # Deps Playwright checks for (maps the apt list to Nix pkgs)
  "glib", "nss", "nspr", "dbus", "at-spi2-core", "atk", "atkmm", "atk",
  "cups", "alsa-lib",
  "freetype", "fontconfig", "pango", "cairo", "gdk-pixbuf", "gtk3",
  "libdrm", "mesa", "mesa.drivers", "libxkbcommon",
  "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext",
  "xorg.libXfixes", "xorg.libXrandr", "xorg.libXrender", "xorg.libXi",
  "xorg.libxcb", "xorg.libXcursor", "xorg.libxshmfence", "xorg.libXinerama"
]

[start]
# Do NOT auto-download browsers; use the Nix-provided ones.
cmd = "python -u main.py"
