# nixpacks.toml

[phases.setup]
nixPkgs = [
  "python311", "python311Packages.pip",
  "chromium", "firefox",                       # ← system browsers from Nix
  # headless deps
  "glib", "nss", "nspr", "dbus", "at-spi2-core", "atk",
  "cups", "alsa-lib",
  "freetype", "fontconfig", "pango", "cairo", "gdk-pixbuf", "gtk3",
  "libdrm", "mesa", "mesa.drivers", "libxkbcommon",
  "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext",
  "xorg.libXfixes", "xorg.libXrandr", "xorg.libXrender", "xorg.libXi",
  "xorg.libxcb", "xorg.libXcursor", "xorg.libxshmfence", "xorg.libXinerama"
]

[start]
# Use system browsers; no playwright install step.
cmd = "python -u main.py"
